### ISSUE TITLE
run nwbuild from source

### ISSUE THREAD

**Issue by linquize** [nwjs/nw-builder#339]
I run `bin/nwbuild` from source directly, but encounter below error.

```
/x/nw-builder/node_modules/update-notifier/index.js:27
                throw new Error('pkg.name and pkg.version required');
                ^

Error: pkg.name and pkg.version required
    at new UpdateNotifier (/x/nw-builder/node_modules/update-notifier/index.js:27:9)
    at module.exports (/x/nw-builder/node_modules/update-notifier/index.js:131:23)
    at Object.<anonymous> (/x/nw-builder/bin/nwbuild:50:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

I have to modify `bin/nwbuild` in order to run successfully

```
--- a/bin/nwbuild
+++ b/bin/nwbuild
@@ -48,7 +48,9 @@ if (argv.h || argv.help) {
 
 var notifier = updateNotifier({
    packagePath: './../package.json'
+    , packageName: "nw-builder"
+    , packageVersion: "2.2.4"
 });
 if (notifier.update) {
     notifier.notify();
```

**Comment by RedSparr0w** [comment]
getting same error

**Comment by adam-lynch** [comment]
Sorry about that! 😳. 2.2.5 released
