### ISSUE TITLE
nwbuild can't find nwjs.app

### ISSUE THREAD

**Issue by finscn** [nwjs/nw-builder#362]
error log:

rocky@rocky-MacBook-Pro test [* master]$ nwbuild -r client
Latest Version: v0.17.3
Using v0.17.3 (sdk)
Create cache folder in /Users/rocky/.nvm/versions/node/v6.5.0/lib/node_modules/nw-builder/cache/0.17.3-sdk
Downloading: http://dl.nwjs.io/v0.17.3/nwjs-sdk-v0.17.3-osx-x64.zip
  downloading [====================] 100% 0.0s

Launching App
App launch error: Error: spawn /Users/rocky/.nvm/versions/node/v6.5.0/lib/node_modules/nw-builder/cache/0.17.3-sdk/osx64/nwjs.app/Contents/MacOS/nwjs ENOENT
{ Error: spawn /Users/rocky/.nvm/versions/node/v6.5.0/lib/node_modules/nw-builder/cache/0.17.3-sdk/osx64/nwjs.app/Contents/MacOS/nwjs ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /Users/rocky/.nvm/versions/node/v6.5.0/lib/node_modules/nw-builder/cache/0.17.3-sdk/osx64/nwjs.app/Contents/MacOS/nwjs',
  path: '/Users/rocky/.nvm/versions/node/v6.5.0/lib/node_modules/nw-builder/cache/0.17.3-sdk/osx64/nwjs.app/Contents/MacOS/nwjs',
  spawnargs: 
   [ '--enable-logging',
     '/Users/rocky/DEV/www/TinyArena/test/client/',
     '-r',
     'client' ] }

-------------

I found that 
the nwjs.app is at 
/Users/rocky/.nvm/versions/node/v6.5.0/lib/node_modules/nw-builder/cache/0.17.3-sdk/osx64/nwjs-sdk-v0.17.3-osx-x64

but nwbuild found it at 
/Users/rocky/.nvm/versions/node/v6.5.0/lib/node_modules/nw-builder/cache/0.17.3-sdk/osx64

**Comment by finscn** [comment]
There is no this bug  in  nw.js 0.17.4 .
