### ISSUE TITLE
Problem with ffmpegsumo.dll

### ISSUE THREAD

**Issue by agrapps** [nwjs/nw-builder#420]
Hi im getting this error when i run my command "nwbuild -v 0.19.5 -p win32,win64 ./" to generate my project I have been looking for ffmpegsumo.dll on internet but i havent found it.
This is the error i get:
`C:\xampp\htdocs\nwjs>nwbuild -v 0.19.5 -p win32,win64 ./
Using v0.19.5
Create cache folder in C:\Users\Alberto\AppData\Roaming\npm\node_modules\node-webkit-builder\cache\0.19.5
Downloading: http://dl.nwjs.io/v0.19.5/nwjs-v0.19.5-win-ia32.zip
Create cache folder in C:\Users\Alberto\AppData\Roaming\npm\node_modules\node-webkit-builder\cache\0.19.5
Downloading: http://dl.nwjs.io/v0.19.5/nwjs-v0.19.5-win-x64.zip
  downloading [====================] 100% 0.0s

Create release folder in C:\xampp\htdocs\nwjs\build\helloworld\win32
Create release folder in C:\xampp\htdocs\nwjs\build\helloworld\win64
{ Error: ENOENT: no such file or directory, lstat 'C:\Users\Alberto\AppData\Roaming\npm\node_modules\node-webkit-builder\cache\0.19.5\win32\ffmpegsumo.dll'
    at Error (native)
    at Object.fs.lstatSync (fs.js:982:18)
    at Object.lstatSync (C:\Users\Alberto\AppData\Roaming\npm\node_modules\node-webkit-builder\node_modules\fs-extra\node_modules\graceful-fs\polyfills.js:297:22)
    at C:\Users\Alberto\AppData\Roaming\npm\node_modules\node-webkit-builder\lib\utils.js:86:28
    at tryCatch2 (C:\Users\Alberto\AppData\Roaming\npm\node_modules\node-webkit-builder\node_modules\bluebird\js\main\util.js:73:19)
    at Promise$_resolveFromResolver [as _resolveFromResolver] (C:\Users\Alberto\AppData\Roaming\npm\node_modules\node-webkit-builder\node_modules\bluebird\js\main\promise.js:595:13)
    at new Promise (C:\Users\Alberto\AppData\Roaming\npm\node_modules\node-webkit-builder\node_modules\bluebird\js\main\promise.js:87:37)
    at Object.copyFile (C:\Users\Alberto\AppData\Roaming\npm\node_modules\node-webkit-builder\lib\utils.js:85:16)
    at C:\Users\Alberto\AppData\Roaming\npm\node_modules\node-webkit-builder\lib\index.js:351:36
    at Array.forEach (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'C:\\Users\\Alberto\\AppData\\Roaming\\npm\\node_modules\\node-webkit-builder\\cache\\0.19.5\\win32\\ffmpegsumo.dll' }
`
On my pc i have:
node-js v6.9.1
nwbuild -v 0.19.5 
Windows 10 64 bits

My package.json is:
`{
  "name": "helloworld",
  "main": "index.html",
  "version": "1.0",
  "window":{
  	"width":640,
  	"height":480
  }
}`

And on my index.html i only display the text hello world on body tags

Does any body know whats this problem?

**Comment by agrapps** [comment]
Already could solve the problem by installing nwbuild with this command
npm install nw-builder -g

Intead of
npm install node-webkit-builder -g

Best regards

**Comment by a4amaan** [comment]
@adam-lynch Thanks.
